mysql:
  dsn: "root:root@tcp(localhost:3306)/kstack"

redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:12379"

grpc:
  server:
    name: "search"
    weight: 100
    addr: ":19091"
    etcdTTL: 60

kafka:
  addrs:
    - "localhost:9094"

es:
  url: "http://localhost:9200"
  sniff: false